# Generated by Django 5.0.6 on 2024-08-30 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255, null=True)),
                ('senha', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
